# Generated by Django 2.2 on 2020-03-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_type', models.IntegerField(choices=[(1, 'User'), (2, 'Admin'), (3, 'SUPER_USER')], default=1)),
                ('password', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=10)),
                ('friend_card', models.IntegerField()),
                ('regis_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
