# Generated by Django 2.2 on 2020-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_card',
            field=models.CharField(max_length=10),
        ),
    ]
