# Generated by Django 2.2 on 2020-03-30 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200329_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Relevant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=8),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32)),
                ('hans', models.CharField(max_length=128)),
                ('contributor', models.ManyToManyField(related_name='_word_contributor_+', to='users.User')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('public_user', models.ManyToManyField(related_name='_word_public_user_+', to='users.User')),
                ('relevant', models.ManyToManyField(related_name='_word_relevant_+', to='users.Relevant')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_eng', models.CharField(max_length=256)),
                ('sentence_hans', models.CharField(max_length=256)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_eng', models.CharField(max_length=64)),
                ('phrase_hans', models.CharField(max_length=64)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Word')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('click_num', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Category')),
                ('contributor', models.ManyToManyField(related_name='_blog_contributor_+', to='users.User')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('tag', models.ManyToManyField(to='users.Tag')),
            ],
        ),
    ]
