# Generated by Django 2.2 on 2020-03-30 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200330_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='contributor',
            field=models.ManyToManyField(default=None, related_name='_blog_contributor_+', to='users.User'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '管理员'), (3, '超级管理员')], default=1),
        ),
    ]
