# Generated by Django 2.2 on 2020-04-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200401_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='contributor',
            field=models.ManyToManyField(default=None, null=True, related_name='_blog_contributor_+', to='users.User'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('startDay', models.CharField(max_length=32)),
                ('endDay', models.CharField(max_length=32)),
                ('tag', models.ManyToManyField(to='users.TaskTag')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
