# Generated by Django 2.2 on 2020-04-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200401_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='contributor',
            field=models.ManyToManyField(default=None, related_name='_blog_contributor_+', to='users.User'),
        ),
    ]
