# Generated by Django 2.2 on 2020-04-02 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
