# Generated by Django 2.2 on 2020-04-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200402_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='finishTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=64)),
                ('startDay', models.CharField(max_length=32)),
                ('endDay', models.CharField(max_length=32)),
                ('finishDay', models.CharField(max_length=32)),
                ('tag', models.ManyToManyField(to='users.TaskTag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
