# Generated by Django 2.2 on 2020-04-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_finishtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishtask',
            name='advance',
            field=models.IntegerField(default=0),
        ),
    ]
