# Generated by Django 2.2 on 2020-04-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_finishtask_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='interval',
            field=models.IntegerField(default=3),
        ),
    ]
