# Generated by Django 2.2 on 2020-04-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_task_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishtask',
            name='interval',
            field=models.IntegerField(default=3),
        ),
    ]
