# Generated by Django 2.2 on 2020-04-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200404_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
