# Generated by Django 2.2 on 2020-04-27 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200427_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecomment',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='basecomment',
            name='name',
        ),
        migrations.AddField(
            model_name='basecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
