# Generated by Django 2.2 on 2020-04-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200427_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecomment',
            name='replied_name',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='multiple_comment',
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('basecomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.BaseComment')),
                ('replied_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BlogComment')),
            ],
            bases=('users.basecomment',),
        ),
    ]
