# Generated by Django 2.2.5 on 2020-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200504_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
