# Generated by Django 2.2.5 on 2020-05-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200522_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
