# Generated by Django 2.2.5 on 2020-05-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200522_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinfo',
            name='user_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chatinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
